version: "3"
services:
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
    ports:
      - 33060:3306
  web:
    build: .
    env_file:
      - .env
    command: yarn start
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_started
  