version: "3"
services:
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=test123
    ports:
      - 33060:3306
    volumes:
      - my-datavolume:/var/lib/mysql
  web:
    build: .
    env_file:
      - .env
    command: yarn start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_started
    restart: always
volumes:
  my-datavolume:
  